print ("Evaluación N°1 Programación y Redes Virtualizadas de Luciano Mendez")
nombre = input("¿Cuál es su nombre?: ")
apellido = input("¿Cuál es su apellido?: ")  
sección = input("¿Cuál es su código y sección de la asignatura?: ")
sede = input("¿Cuál es su sede?: ")
print ("Usted es de la sede",sede," de la asignatura ",sección, "El nombre del alumno",nombre ,apellido)
